// ── Email templates ────────────────────────────────────────────────────────

export function buildHtml({
  productName,
  productUrl,
  gapDetails,
  portalUrl,
  token,
}: {
  productName: string;
  productUrl: string;
  gapDetails: { name: string; hint: string; required: boolean }[];
  portalUrl: string;
  token: string;
}): string {
  const rows = gapDetails
    .map(
      (g) => `
      <tr>
        <td style="padding:9px 14px;border-bottom:1px solid #DCDCE0;font-family:'Courier New',monospace;font-size:12px;color:#17181A;white-space:nowrap;">
          ${g.name}${g.required ? '<span style="color:#B8760B;"> *</span>' : ""}
        </td>
        <td style="padding:9px 14px;border-bottom:1px solid #DCDCE0;font-size:13px;color:#6E6E73;">${g.hint}</td>
      </tr>`
    )
    .join("");

  const productLink = productUrl
    ? `<a href="${productUrl}" style="color:#0B5FD0;">${productUrl}</a>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MIA — Product data request</title></head>
<body style="margin:0;padding:0;background:#F5F5F7;font-family:Inter,system-ui,-apple-system,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
    <tr><td align="center" style="padding:48px 20px;">
      <table width="560" cellpadding="0" cellspacing="0" role="presentation"
             style="background:#FFFFFF;border-radius:16px;overflow:hidden;border:1px solid #DCDCE0;">

        <!-- Header -->
        <tr><td style="background:#17181A;padding:28px 32px;">
          <p style="margin:0 0 6px;font-size:10px;letter-spacing:0.18em;text-transform:uppercase;color:rgba(255,255,255,0.4);font-family:'Courier New',monospace;">
            MIA &mdash; Digital Product Passport
          </p>
          <h1 style="margin:0;font-size:20px;font-weight:600;color:#FFFFFF;letter-spacing:-0.02em;">
            Product data request
          </h1>
        </td></tr>

        <!-- Body -->
        <tr><td style="padding:28px 32px;">
          <p style="margin:0 0 16px;font-size:15px;line-height:1.65;color:#17181A;">
            We are generating a <strong>Digital Product Passport (DPP)</strong> for
            <strong>${productName}</strong>${productLink ? ` (${productLink})` : ""}
            to meet EU ESPR compliance requirements.
          </p>
          <p style="margin:0 0 22px;font-size:15px;line-height:1.65;color:#17181A;">
            The ${gapDetails.length} field${gapDetails.length > 1 ? "s" : ""} below
            ${gapDetails.length > 1 ? "are" : "is"} required but could not be found on the product page.
            Please provide ${gapDetails.length > 1 ? "them" : "it"} using the button below &mdash;
            it takes less than two minutes.
          </p>

          <!-- Gap table -->
          <table width="100%" cellpadding="0" cellspacing="0" role="presentation"
                 style="border:1px solid #DCDCE0;border-radius:8px;overflow:hidden;margin-bottom:10px;">
            <tr style="background:#F5F5F7;">
              <th style="padding:9px 14px;text-align:left;font-size:10px;letter-spacing:0.12em;text-transform:uppercase;color:#6E6E73;font-weight:500;">Field</th>
              <th style="padding:9px 14px;text-align:left;font-size:10px;letter-spacing:0.12em;text-transform:uppercase;color:#6E6E73;font-weight:500;">What we need</th>
            </tr>
            ${rows}
          </table>
          <p style="margin:0 0 28px;font-size:11px;color:#6E6E73;">* Required for compliance</p>

          <!-- CTA -->
          <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
            <tr><td align="center" style="padding-bottom:28px;">
              <a href="${portalUrl}"
                 style="display:inline-block;background:#0B5FD0;color:#FFFFFF;text-decoration:none;font-size:15px;font-weight:600;padding:14px 36px;border-radius:100px;letter-spacing:-0.01em;">
                Provide missing data &rarr;
              </a>
            </td></tr>
          </table>

          <!-- Footer note -->
          <p style="margin:0;font-size:12px;line-height:1.6;color:#6E6E73;border-top:1px solid #DCDCE0;padding-top:20px;">
            This request was generated by <strong>MIA</strong> (Mittelstand Integration Agent), a tool for
            EU ESPR Digital Product Passport compliance. If you did not expect this, please ignore this email.
            <br>Reference: <code style="font-family:'Courier New',monospace;background:#F5F5F7;padding:2px 5px;border-radius:3px;">MIA-${token.slice(0, 6)}</code>
          </p>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

export function buildText({
  productName,
  productUrl,
  gapDetails,
  portalUrl,
  token,
}: {
  productName: string;
  productUrl: string;
  gapDetails: { name: string; hint: string; required: boolean }[];
  portalUrl: string;
  token: string;
}): string {
  const fieldLines = gapDetails
    .map((g) => `  - ${g.name}${g.required ? " (required)" : ""}: ${g.hint}`)
    .join("\n");

  return `MIA — Digital Product Passport data request
Reference: MIA-${token.slice(0, 6)}

Hello,

We are generating a Digital Product Passport for ${productName}${productUrl ? ` (${productUrl})` : ""} to meet EU ESPR compliance requirements.

The following ${gapDetails.length} field${gapDetails.length > 1 ? "s are" : " is"} missing:

${fieldLines}

Please fill in the missing data here (takes under 2 minutes):
${portalUrl}

This link is valid for 7 days.

---
Sent by MIA (Mittelstand Integration Agent) — mia-dpp.vercel.app
If you did not expect this request, please ignore this email.`;
}
